[package]
name = "murmur3_nif"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "murmur3_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.36.0"
murmur3 = "0.5.2"
